source 'http://rubygems.org'

gem 'rails'


group :development, :test do
  gem 'rspec'
  gem 'cucumber'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'email_spec'
  gem 'timecop'
  gem 'launchy'
end