source "http://rubygems.org"

group(:test) do
  gem 'bundler'
  gem 'cucumber'
  gem 'capybara'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'activerecord'
  gem 'pg'
  gem 'faker'
  gem 'rake'
  gem 'rspec-expectations'
  gem 'minitest'
  gem 'turn'
end
